[[agents]]
id = "hosting-agent-1"
name = "Hosting Agent 1"
keystore_file = "./agent-1.keystore"
public_address = "HcSCIdm3y8fjJ8g753YEMOo4qdIctqsqrxpIEnph7Fj7dm4ze776bEPDwxoog8a"

[[dnas]]
id = "happ_store_dna"
file = "home/<YOUR_USER_NAME>/.config/holochain/dnas/happ-store.dna.json"
hash = "Qm328wyq38924x"

[[dnas]]
id = "hha_dna"
file = "home/<YOUR_USER_NAME>/.config/holochain/dnas/hha.dna.json"
hash = "QmWVCiHf5GfoUHDcV9JSrUC1UZk1dcP9SECBTgoTKHpzZA"

[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "hosting-agent-1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp/tmp-storage-1"

[[instances]]
id = "hha"
dna = "hha_dna"
agent = "hosting-agent-1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp/tmp-storage-2"

[[interfaces]]
id = "websocket_interface"
admin = false
[interfaces.driver]
type = "websocket"
port = 9000
[[interfaces.instances]]
id = "happ-store"
[[interfaces.instances]]
id = "hha"

[[interfaces]]
id = "http_interface"
admin = true
[interfaces.driver]
type = "http"
port = 3300
[[interfaces.instances]]
id = "happ-store"
[[interfaces.instances]]
id = "hha"

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3001
dna_interface = "websocket_interface"
