# * Copy this file to conductor-config.toml and generate a unique agent key
#   for your instance of Hylo DNA:
#
#    1. Run `hc keygen -n --path keystores/myagent.keystore`
#    2. Copy the public address hash and copy it into public_address below

[[agents]]
id = "hp_admin_agent"
name = "HP Admin Agent"
public_address = "YOUR_PUBLIC_ADDRESS"
keystore_file = "keystores/myagent.keystore"

# The hash field in the dnas below doesn't seem to do anything.

[[dnas]]
id = "happ_store_dna"
file = "/PATH/TO/happ-store.dna.json"
hash = "Qm328wyq38924x"

[[dnas]]
id = "hylo_dna"
file = "/PATH/TO/hylo.dna.json"
hash = "Qm328wyq38924y"

[[dnas]]
id = "hha_dna"
file = "//PATH/TO/HHA/dna-src.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "hp_admin_agent"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-1"

[[instances]]
id = "hylo"
dna = "hylo_dna"
agent = "hp_admin_agent"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-2"

[[instances]]
id = "hha"
dna = "hha_dna"
agent = "hp_admin_agent"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-3"

# -- WS-RPC interface

[[interfaces]]
id = "websocket-interface"

    [[interfaces.instances]]
    id = "hylo"

    [[interfaces.instances]]
    id = "happ-store"

    [[interfaces.instances]]
    id = "hha"
    
    [interfaces.driver]
    type = "websocket"
    port = 3400
