##
# * Copy this file to conductor-config.toml and generate a unique agent key for each of the `agents` fields below:
#
# * Steps for creating an agent:
#    1. Run `hc keygen -n --path keystores/myagent.keystore`
#    2. Copy the public address hash and paste it as the value for the agent's `public_address`
##

# -- All Agents
[[agents]]
id = "hp_admin_agent_1"
name = "HP Admin Agent One"
public_address = "<PUBLIC_ADDRESS_FOR_AGENT_ONE>"
keystore_file = "keystores/myagent.keystore"

[[agents]]
id = "hp_admin_agent_2"
name = "HP Admin Agent Two"
public_address = "<PUBLIC_ADDRESS_FOR_AGENT_TWO>"
keystore_file = "keystores/myagent.keystore"

# -- All DNAs
[[dnas]]
id = "happ_store_dna"
file = "/PATH/TO/happ-store.dna.json"
hash = "currently unused"

[[dnas]]
id = "hylo_dna"
file = "/PATH/TO/hylo.dna.json"
hash = "currently unused"

[[dnas]]
id = "hha_dna"
file = "/PATH/TO/HHA/dna-src.dna.json"
hash = "currently unused"

[[dnas]]
id = "holofuel_dna"
file = "/PATH/TO/holofuel.dna.json"
hash = "currently unused"

# -- Agent Instances for each DNA
[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "hp_admin_agent_1"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-agent1-1"

[[instances]]
id = "hylo"
dna = "hylo_dna"
agent = "hp_admin_agent_1"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-agent1-2"

[[instances]]
id = "hha"
dna = "hha_dna"
agent = "hp_admin_agent_1"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-agent1-3"

[[instances]]
id = "holofuel"
dna = "holofuel_dna"
agent = "hp_admin_agent_1"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-agent1-4"

[[instances]]
id = "holofuel2"
dna = "holofuel_dna"
agent = "hp_admin_agent_2"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "file"
  path = "tmp/tmp-storage-agent2-1"

# -- WS-RPC interface
[[interfaces]]
id = "websocket-interface"

    [interfaces.driver]
    type = "websocket"
    port = 3400

    [[interfaces.instances]]
    id = "hylo"

    [[interfaces.instances]]
    id = "happ-store"

    [[interfaces.instances]]
    id = "hha"

    [[interfaces.instances]]
    id = "holofuel"

    [[interfaces.instances]]
    id = "holofuel2"

# -- HTTP admin interface (currently only used for testing the conductor is running in setup script)
[[interfaces]]
id = 'http-interface'
admin = true

    [interfaces.driver]
    type = "http"
    port = 3300

    [[interfaces.instances]]
    id = "hylo"

    [[interfaces.instances]]
    id = "happ-store"

    [[interfaces.instances]]
    id = "hha"

    [[interfaces.instances]]
    id = "holofuel"

    [[interfaces.instances]]
    id = "holofuel2"

