version: 2.1

commands:
  prepare-env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-yarn-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-yarn-cache-master-{{ .Environment.CIRCLE_JOB }}
  prepare-lint:
    steps:
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
  setup-nodejs:
    steps:
      - prepare-env
      - run:
          name: Yarn Versions
          command: yarn versions
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Webpack build
          command: yarn build
      - save-npm-cache
  run-tests:
    steps:
      - setup-nodejs
      - run:
          name: Test
          command: yarn test
  run-lint:
    steps:
      - prepare-env
      - prepare-lint
      - run:
          name: Lint
          command: yarn test:lint
  save-npm-cache:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-yarn-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test-node-v10:
    docker:
      - image: node:10
    steps:
      - run-tests
  lint-node-v10:
    docker:
      - image: node:10
    steps:
      - run-lint

workflows:
  test:
    jobs:
      - test-node-v10
      - lint-node-v10
